config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
  get 'admin', to: 'admin#index'
  get 'admin/posts'
  get 'admin/comments'
  get 'admin/users'
  get 'admin/show_post/:id', to: "admin#show_post", as: "admin_post"
end

root "home#index"

get "/home", to: "home#index"
get '/search', to: "search#index"
get '/about', to: "about#show"


  devise_for :users
    resources :contacts, only: [:new, :create]
  resources :posts do
  resources :comments


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
#root :to => "home#index"

 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
    :subject => "Contact Form",
    :to => "quirky@ncril.com",
    :from => %("#{name}" <#{email}>)
    }
 end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, :presence => true
 validates :title, :presence => true,
                   :length => { :minimum => 5, maximum: 50 }
validates :content, :presence => true,
          :length => { :minimum => 10, maximum: 2000 }

has_many :comments, :dependent => :destroy
has_many :tags




accepts_nested_attributes_for :tags, :allow_destroy => :true,
:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy

         enum role: [:user, :moderator, :admin]
         after_initialize :set_default_role, :if => :new_record?

         private
         def set_default_role
           self.role ||= :user



         end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def posts
    @posts = Post.all.includes(:user, :comments)
  end

  def comments
  end

  def users
  end

  def show_post
    @post = Post.includes(:user, :comments).find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #http_basic_authenticate_with :name => "dhh", :password => "secret"
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json {render :json => @posts }
    end
  end


  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :body)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin,resource]), class:'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
<p>
<%= link_to "Admin", admin_path %> <%= " > #{params[:action].capitalize}" unless params[:action].eql?("index")%>
  </p>
  <div class="btn-group">
    <%= render "admin/link", resource: Post %>
    <%= render "admin/link", resource: Comment %>
    <%= render "admin/link", resource: User %>
  </div>
</div>

app/views/admin/comments.html.erb
<h1>Admin#comments</h1>
<div class="container">
 <h1 class="text-center">Adminstrator</h1>
 <%= render 'admin/nav_links'%>
</div>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<div class="container">
 <h1 class="text-center">Adminstrator</h1>
 <%= render 'admin/nav_links'%>  
</div>

app/views/admin/posts.html.erb
<h1>Admin#posts</h1>
<div class="container">
 <h1 class="text-center">Adminstrator</h1>
 <%= render 'admin/nav_links'%>
<table class="table table-dark table-striped">
     <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Post</th>
        <th scope="col">Author</th>
        <th scope="col">Comments</th>

      </tr>
     </thead>
     <tbody>
      <%= @post.each do |post| %>
      <tr>
             <th scope="row"> <%= post.id %> </th>
             <td><%= link_to post.title.truncate(15), admin_post_path(post) %> </td>
             <td> <%= post.user.name %></td>
             <td><%= pluralize(post.comments.size, "Comment")%></td>
             </tr
      <% end %>
     </tbody>
</table>
</div>

app/views/admin/show_post.html.erb
<h1>Admin#show_post</h1>
<div class="container">
 <h1 class="text-center">Adminstrator</h1>
 <%= render 'admin/nav_links'%>
 <div class="text-center mt-5">
   <div class="btn-group">
     <%= link_to "Edit", edit_post_path(@post), class:"btn btn-warning" %>
     <%= button_to "delete", @post, method: :delete, data: { confirm: "Are you sure?"}, class:"btn btn-danger" %>
   </div>
 </div>
<div class="row mt-1">
  <p>
   <strong>Title:</strong> <%= @post.title %>
  </p>
</div>
</div>
<div class="row mt-1">
<p>
  <strong>Views:</strong> <%= @post.views %>
</p>
</div>
<div class="row mt-1">
  <p><strong>Author:</strong>>
  <%= "#{@post.user.email} | #{@post.user.name} | #{pluralize(@post.user.views, "View")}" %>
  </p>
</div>
<div class="row mt-1">
  <strong>Body:</strong> <%= @post.body %>
</div>
<div class="row mt-1">
  <strong> <%= pluralize(@post.comments.count, "Comment") %>:</strong>
  <% @post.comments.each do |comment| %>
  <div class="row mt-1">
    <%= comment.user.name %>
    <%= comment.body %>
    <% end %>
  </div>
</div>

app/views/admin/users.html.erb
<h1>Admin#users</h1>
<div class="container">
 <h1 class="text-center">Adminstrator</h1>
 <%= render 'admin/nav_links'%>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quirky Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>
<body style="background: #EEEEEE;" >
  <nav class="navbar navbar-light navbar-expand-lg navigation-clean-search" style="background: #dabdad;">
      <div class="container">
        <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="navbar-brand">Quirky Blog</h1>
         <% end %>

          <div class="collapse navbar-collapse" id="navcol-1">
              <ul class="navbar-nav">
                  <li class="nav-item"><%= link_to root_path, class: "navbar-item" do %><p class="nav-link active" style="color: #000000;">Home</p> <% end %> </li>
                  <li class="nav-item"><%= link_to posts_path class: "navbar-item" do %><p class="nav-link active" style="color: #000000;">Feed</p><% end %> </li>
                  <li class="nav-item"><%= link_to new_contact_path, class: "navbar-item" do %><p class="nav-link active" style="color: #000000;">Contact</p> <% end %> </li>
                  <li class="nav-item"><%= link_to about_path, class: "navbar-item" do %><p class="nav-link active" style="color: #000000;">About</p> <% end %> </li>

              </ul>
            <%= render "search/form" %>
                <%= link_to '<button class="btn btn-light action-button" role="button" type="button" style="background: #d49a6a;">Admin Mode</button>'.html_safe, admin_path %>
      </div>
    </div>

    <!--mobile version of the website-->
    <div id="navbarExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="field is-grouped">
          <p class="control">
          <%= link_to "New post", new_post_path, class: "button is-info is-inverted" %>
          </p>
          <p class="control">Sign Up</p>
        </div>
      </div>
    </div>

  </nav>
    <%= yield %>

  <footer class="boxed">
   <div class="container">
      <div class="row">
         <div class="col-mid-10 col-gg-8 mx-ayo">
           <u class="list-inline text-center">
            <div class=center
              <li class="list-inline-item">
                <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </li>
              <li class="list-inline-item">
                <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
              </li>
              <li class="list-inline-item">
                <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </li>
              </div>
           </u>
           <div class="name">
           <p class="text-muted copyright">Copyright Quirky Blog 2024</p>
           </div>
         </div>
      </div>
   </div>
  </footer>
  </body>
</html>