config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
  get 'admin', to: 'admin#index'
  get 'admin/posts'
  get 'admin/comments'
  get 'admin/users'
  get 'admin/show_post/:id', to: "admin#show_post", as: "admin_post"
end

root "home#index"

get "/home", to: "home#index"
get '/search', to: "search#index"
get '/about', to: "about#show"


  devise_for :users
    resources :contacts, only: [:new, :create]
  resources :posts do
  resources :comments


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
#root :to => "home#index"

 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
    :subject => "Contact Form",
    :to => "quirky@ncril.com",
    :from => %("#{name}" <#{email}>)
    }
 end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, :presence => true
 validates :title, :presence => true,
                   :length => { :minimum => 5, maximum: 50 }
validates :content, :presence => true,
          :length => { :minimum => 10, maximum: 2000 }

has_many :comments, :dependent => :destroy
has_many :tags




accepts_nested_attributes_for :tags, :allow_destroy => :true,
:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy

         enum role: [:user, :moderator, :admin]
         after_initialize :set_default_role, :if => :new_record?

         private
         def set_default_role
           self.role ||= :user



         end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def posts
    @posts = Post.all.includes(:user, :comments)
  end

  def comments
  end

  def users
  end

  def show_post
    @post = Post.includes(:user, :comments).find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #http_basic_authenticate_with :name => "dhh", :password => "secret"
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json {render :json => @posts }
    end
  end


  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :body)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  @query = Post.ransack(params[:q])
  @post = @query.result(distinct: true)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/about/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Add your head content here -->
</head>

<body>
  <header class="masthead">
    <div class="container">
      <div class="row">
        <div class="position-point">
          <h1 class="text">Nice to meet you</h1>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <section class="team-boxed">
      <div class="container">
        <div class="intro">
          <h2 class="text-center">About Us</h2>
          <p class="text-center">Visitors can click through different stories about the brand’s sponsorships, like providing gear for Heroes and Horses.</p>
          <p class="text-center">It also showcases stories about inspiring people from the outdoors scene, such as the story behind Mark Engler, a legendary fishing guide in the Colorado/New Mexico area.</p>
          <p class="text-center">SS tells its story. It also features key highlights about the brand that keeps visitors inspired and creates a good user experience.</p>
          <p class="text-center">These summaries help showcase SS unique qualities and earn trust with potential customers. </p>
        </div>

        <div class="row people">
          <div class="col-md-4">
            <div class="box text-center">
              <!-- Image -->
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnM0_-e8cvsICiqsrFkEVoY24yHYD9AN-AGqK-Tz9uVj_Ef6kZOZ0M-Lrg0VPJ-7giV0I&usqp=CAU" alt="Ben Johnson Image" class="img-fluid">
              <h3 class="name">Ben Johnson</h3>
              <p class="title">Musician</p>
              <p class="description">ZYX</p>
              <div class="social">
                <a href="">
                  <i class="fa fa-facebook-official"></i>
                </a>
                <a href="">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="">
                  <i class="fa fa-instagram"></i>
                </a>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="box text-center">
              <!-- Image -->
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqcwCHFqhqMqdmotU7mIXg9JxUDriNK_CzyMd4IUnu19vX99dK35RyG4IlRmA5ylit1Qw&usqp=CAU" alt="Emily C Image" class="img-fluid">
              <h3 class="name">Emily C</h3>
              <p class="title">Artist</p>
              <p class="description">XYZ</p>
              <div class="social">
                <a href="">
                  <i class="fa fa-facebook-official"></i>
                </a>
                <a href="">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="">
                  <i class="fa fa-instagram"></i>
                </a>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="box text-center">
              <!-- Image -->
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS69jJH3G0Mtt_kYLxQkUZJ2-WUgOd_PCU_O6Rji7Ql-y2IOW0fW1nxikAx9e7nsHB1Wq0&usqp=CAU" alt="Carl Kent Image" class="img-fluid">
              <h3 class="name">Carl Kent</h3>
              <p class="title">Stylist</p>
              <p class="description">ZYX</p>
              <div class="social">
                <a href="">
                  <i class="fa fa-facebook-official"></i>
                </a>
                <a href="">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="">
                  <i class="fa fa-instagram"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="highliht-phone">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="intro">
              <!-- Add your content for the highliht-phone section here -->
            </div>
          </div>

          <div class="col-md-4">
            <div class="d-none">
              <!-- Image -->
              <div class="screen">
                <!-- Add your content for the screen image here -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</body>

</html>

app/views/home/index.html.erb
<!--The Main route of the rails server-->

<section class="highlight-clean">
  <div class="container">
    <div class="intro">
      <h1 class="text-center">Homepage</h1>
    </div>
    <div class="button-home">
      <!-- If and else statement to sign the user into the blog-->
      <% if current_user %>
       <p> Hello <%= current_user.email %>!</p>
       <p> You are a [<%= current_user.role %>]</p>

      <p>
        You have successfully signed in
        You can now interact now check the feed<br>
        <%= link_to '<button class="btn btn-primary" role="button" style="background: #055ada;">My Blog</button>'.html_safe, posts_path %>
      </p>
      <%= link_to '<button class="btn btn-primary" role="button" style="background: #d49a6a;">Sign Out</button>'.html_safe, destroy_user_session_path, 'data-turbo-method': :delete %>

      <% else %>
       <p> You are not signed in </p>
       <p>Create an account now</p>
       <%= link_to '<button class="btn btn-primary" role="button" style="background: #055ada;">Register</button>'.html_safe, new_user_registration_path %>
       <br>
       <p>Do you already have an account? Click here to sign in</p>
       <%= link_to '<button class="btn btn-primary" role="button" style="background: #d49a6a;">Sign In</button>'.html_safe, new_user_session_path %>
       <% end %>
    </div>
  </div>
</section>
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
        <%= image_tag 'White-apple.jpg', class: "home-image", style: 'max-width: 60rem;' %>
        <div class="text-center intro-text p-5 rounded bg-faded">
           <div class="text-center">
             <h2 class="section-heading mb-4">
               <span class="section-heading-lower">Create a Post</span>
             </h2>
             <p class="mb-3">Create your first Post now </p>
           </div>
           <div class="mx-auto intro-button">
             <%= link_to '<button class="btn btn-primary" role="button" style="background: #055ada;">My Blog</button>'.html_safe, posts_path %>
           </div>
        </div>
    </div>
  </div>
</section>
<section class="page-section cta">
<div class="social">
  <div class="socialText">
   <h2> Find us on twitter</h2>
  </div>
  <div class="socailIcon">
<a class="twitter-timeline" data-width="500" data-height="500" data-theme="light" href="https://twitter.com/luxurytravel?ref_src=twsrc%5Etfw">Tweets by luxurytravel</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<a href="https://twitter.com/luxurytravel?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-show-count="false">Follow @luxurytravel</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

 </div>
 </div>
</section>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:'d-flex') do |f| %>
<%= f.search_field :title_or_content_or_name_i_cont_any,
 placeholder: "Search...",
 class: "form-control me-2" %>
<%= f.submit "Search!", class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center"><%= pluralize(@post.count, "Your Results") %></h1>
<%= render "search/form" %>

<div class="container">
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
      <th><%= sort_link(@query, :content, "Post Content", default_order: :asc) %> </th>
      <th><%= sort_link(@query, :name, "Users", default_order: :asc) %> </th>
      </tr>
    </thead>

    <tbody>
      <%= @post.each do |post| %>
    <tr>
    <td> <%= link_to post.title, post %></td>
     <td> <%=  post.content.truncate_words(25) %></td>
    <td> <%= link_to post.name, post %></td>
    </tr>
    <% end %>
    </tbody>
    </table>
  </div>